development:
  adapter: postgresql
  encoding: unicode
  database: breezy_development
  pool: 5
  username: breezy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: breezy_test
  pool: 5
  username: breezy
  password:


production:
  adapter: postgresql
  encoding: unicode
  database: breezy_production
  pool: 5
  username: breezy
  password: 
